# Generated by Django 5.1.2 on 2024-11-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookimage',
            field=models.ImageField(default='default.jpg', upload_to='book_images/'),
        ),
    ]
